global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka:9999']
    metrics_path: /metrics

  - job_name: 'crypto-api'
    static_configs:
      - targets: ['crypto-api:5000']
    metrics_path: /metrics
